### ISSUE TITLE
[CHORE]  Add issue template

### ISSUE THREAD

**Issue by RakeshSangem** [avie-dev/spaceslounge#13]
Having an Issue template will be really helpful.

We easily track the issues like:
- Docs
- Feature
- Bug

I would like to add issue templates to this project. Thanks in advance!

**Comment by alisamadiii** [comment]
Perfect @RakeshSangem

**Comment by alisamadiii** [comment]
@RakeshSangem 
Are you done with the issue?

**Comment by RakeshSangem** [comment]
> Collaborator

Sorry, I was busy. Today I'll finish the task:)
