### ISSUE TITLE
[FEATURE] Add Sign-up page.

### ISSUE THREAD

**Issue by jaynarayan-vaishnav** [avie-dev/spaceslounge#14]
add sign-up page with its contents.

**Comment by devvsakib** [comment]
@AliReza1083  you can assign this task to me

**Comment by alisamadiii** [comment]
Hey @devvsakib,
It's already been assigned to someone, If you want to take the task, You must talk with the person that has been assigned before.
If they're agree, then We'll assign it to you.

**Comment by jaynarayan-vaishnav** [comment]
@devvsakib i am already working on this task  can you work on some other issues for this project till that moment it 🙂

**Comment by devvsakib** [comment]
> Hey @devvsakib,
> It's already been assigned to someone, If you want to take the task, You must talk with the person that has been assigned before.
> If they're agree, then We'll assign it to you.

sureee, its been long time so i thought he maybe not working,😂😂😂😂

**Comment by alisamadiii** [comment]
> > Hey @devvsakib,
> > It's already been assigned to someone, If you want to take the task, You must talk with the person that has been assigned before.
> > If they're agree, then We'll assign it to you.
> 
> sureee, its been long time so i thought he maybe not working,😂😂😂😂

They are having Wi-Fi issue.
Do you want to make the `space light` page?

**Comment by alisamadiii** [comment]
How is it going Jay?
