### ISSUE TITLE
Add a contributor page 

### ISSUE THREAD

**Issue by avie-dev** [avie-dev/spaceslounge#22]
Add a list of contributors on the spaces lounge site.

- [x] design
- [x] code
- [ ] user test

**Comment by alisamadiii** [comment]
Awesome

**Comment by alisamadiii** [comment]
@Mayank-KS 
How is it going?

**Comment by Mayank-KS** [comment]
> @Mayank-KS How is it going?

yeah work in progress, busy with college stuff so it is hard to find time for it

Is there any urgency??

**Comment by alisamadiii** [comment]
@Mayank-KS 
Just wanted know how the project is going.

**Comment by devvsakib** [comment]
@AliReza1083  you can drop it to me

**Comment by alisamadiii** [comment]
@devvsakib Sorry for late answer...
It was assigned to @Mayank-KS

**Comment by alisamadiii** [comment]
is there any updates Mayank?

**Comment by alisamadiii** [comment]
Done by Mayank ✅
