### ISSUE TITLE
404 pages

### ISSUE THREAD

**Issue by alisamadiii** [avie-dev/spaceslounge#23]
if the user goes to a page which doesn't exist, The page must bring something for the user.
We have to make 404 page.

- [x] Desgin
- [ ] Code
- [ ] Test the website

**Comment by AashviKothari** [comment]
Kindly assign me the task

**Comment by alisamadiii** [comment]
> Kindly assign me the task

Feel free to do it anytime, anytime that you are free.

**Comment by thevinitgupta** [comment]
@AliReza1083 I would like to work on this if no one is working

**Comment by alisamadiii** [comment]
> @AliReza1083 I would like to work on this if no one is working

This issue has been assigned to @AashviKothari, and We have to ask them whether they are able to do it or now.
We will let you.

**Comment by thevinitgupta** [comment]
Sure thing. Actually I saw the website and the 404 page was not designed.
After searching through issues, I found this thread for the 404 page design.

**Comment by thevinitgupta** [comment]
@AliReza1083 she has not responded.
Can I start working?

**Comment by alisamadiii** [comment]
> @AliReza1083 she has not responded. Can I start working?

Sorry, They said: "give us 3 days".
If They won't be able to do it, then We will assign this issue to you.
Thanks for waiting :)

**Comment by thevinitgupta** [comment]
Sure thanks

**Comment by thevinitgupta** [comment]
@AliReza1083 any updates regarding the development?

**Comment by alisamadiii** [comment]
@thevinitgupta 
This issue will be assigned to you.
Good luck :)

**Comment by alisamadiii** [comment]
How is it going @thevinitgupta ?

**Comment by thevinitgupta** [comment]
I have started working on the page.

**Comment by alisamadiii** [comment]
How is it going? 
@thevinitgupta

**Comment by thevinitgupta** [comment]
@AliReza1083 I have made the PR
