### ISSUE TITLE
feat: Footer

### ISSUE THREAD

**Issue by zelfroster** [avie-dev/spaceslounge#32]
### This project currently does not have a footer. So, I want to create a footer for this project.
- Footer Design - 
![image](https://user-images.githubusercontent.com/93514460/200289320-6b51e80b-7eb2-4a1f-a2bf-7703b59b6bf5.png)
Can I work on it?

**Comment by jaynarayan-vaishnav** [comment]
@zelfroster  I assigned it to you feel free to work on it

**Comment by zelfroster** [comment]
Thanks @jaynarayan-vaishnav .
Also, Is there a deadline to complete it?
I am a bit busy so will do it at night.

**Comment by jaynarayan-vaishnav** [comment]
No problem you can finish it when you have time 🙂

**Comment by alisamadiii** [comment]
How is it going @zelfroster ?

**Comment by zelfroster** [comment]
> How is it going @zelfroster ?

I already did it yesterday. But I am not sure about the content I should include in the Footer.
I will discuss in the Discord today.

**Comment by alisamadiii** [comment]
> > How is it going @zelfroster ?
> 
> I already did it yesterday. But I am not sure about the content I should include in the Footer. I will discuss in the Discord today.

Awesome

**Comment by devvsakib** [comment]
@AliReza1083  im free to do this❄️

**Comment by alisamadiii** [comment]
Done by @devvsakib
