### ISSUE TITLE
Information about the Website

### ISSUE THREAD

**Issue by alisamadiii** [avie-dev/spaceslounge#34]
### Description

In the website, There are two section that need someone to write something about the website...
1. What is Spaces Lounge? `Right now there are 3 items for description, you can add more than that If you want`
2. Why Spaces Lounge?

Tasks for this issue:
- [x] What is Spaces Lounge?
- [x] Why Spaces Lounge?

### Screenshots

![image](https://user-images.githubusercontent.com/99729607/200465674-656605c0-7ab5-4651-872b-ec557185695e.png)

**Comment by alisamadiii** [comment]
How is it going?

**Comment by Kellsonphilips** [comment]
Good issue here

**Comment by Kellsonphilips** [comment]
Why is it still not done yet?

**Comment by alisamadiii** [comment]
We're working on it,
Sorry for the delay

**Comment by Kellsonphilips** [comment]
It's alright, maybe I will look into it later on

**Comment by alisamadiii** [comment]
Done ✅
