### ISSUE TITLE
Tooltip information

### ISSUE THREAD

**Issue by alisamadiii** [avie-dev/spaceslounge#38]
### Description

I want to add a button at the corner of the page, when the user clicks it, they will see something.

### Screenshots

![image](https://user-images.githubusercontent.com/99729607/201520819-9fd95a52-1783-434a-a319-fa8b15664a94.png)

**Comment by jaynarayan-vaishnav** [comment]
you want to add the button for what purpose??
can you elobrate?

**Comment by alisamadiii** [comment]
> you want to add the button for what purpose?? can you elobrate?

for telling a short info about this project or we can write something else...

**Comment by jaynarayan-vaishnav** [comment]
We are already providing the info on the homepage right?? If yes then we don't need this button in my opinion
Or we can also remove the info about the project from the homepage and add this button instead of it.

**Comment by alisamadiii** [comment]
> We are already providing the info on the homepage right?? If yes then we don't need this button in my opinion Or we can also remove the info about the project from the homepage and add this button instead of it.

We can also add something else instead of info.

**Comment by jaynarayan-vaishnav** [comment]
Yup we can do that let's wait for others to see this issue maybe they'll come up with a suggestion 🙂
