### ISSUE TITLE
[FEATURE] Speaker Dashboard

### ISSUE THREAD

**Issue by alisamadiii** [avie-dev/spaceslounge#49]
### Description

We need to make the `Speaker-Dashboard`.

- [ ] Speaker-Dashboard

### Screenshots

![image](https://user-images.githubusercontent.com/99729607/211147147-d6b7d3a6-b4a2-4645-933c-6b5e876c196f.png)
![image](https://user-images.githubusercontent.com/99729607/211147155-40a5e652-8c9a-4b59-95d3-bc8cf1d80601.png)

**Comment by jaynarayan-vaishnav** [comment]
Assign it to me @AliReza1083

**Comment by alisamadiii** [comment]
Awesome Jay,
This issue will be assigned to you.

 🗓️Deadline:  16 January 2023

**Comment by alisamadiii** [comment]
How is it going?

**Comment by jaynarayan-vaishnav** [comment]
Assigning this issue to Ali as i am busy and not able to complete it on time sorry for that.
