### ISSUE TITLE
[FEATURE] Space page light

### ISSUE THREAD

**Issue by alisamadiii** [avie-dev/spaceslounge#50]
### Description

We need to make the `Space-Light` page.

- [ ] Space page light

### Screenshots

![image](https://user-images.githubusercontent.com/99729607/211147233-537932c1-601d-4374-9a96-70a1b4866b07.png)

**Comment by thevinitgupta** [comment]
Hi @AliReza1083, I would love to contribute. Could you provide more info about the Space Light page and the tasks required?

**Comment by alisamadiii** [comment]
Hi @thevinitgupta,
It's great that you want to contribute on this project with us.

First of all, We're using `NextJS` & `TailwindCSS`.

The tasks:
- You can see the design [here](https://www.figma.com/file/YMoSJKWhHTakMAWpCozZ7D/Spaces-Lounge?node-id=516%3A197&t=XA53wAjjxi7Tn08q-1)
- Make a file in page folder by the name of `space-light.js`
- turn the design to the code, so that we can have it on website.
- For displaying the data, You can make `json` or `js` for storing data and you can use it in `space-light.js`
- We'll be using Fake data for now.

Hope that makes

I'll be happy to answer your question if there is any doubt or misunderstand 🙏

**Comment by thevinitgupta** [comment]
That works for me. Thanks for the detailed explanation.
Could assign it to me so I can start working?

**Comment by alisamadiii** [comment]
Awesome 🙏,
It'll be assigned to you...
Good Luck

**Comment by alisamadiii** [comment]
One more thing about Design.

For light mode, You can copy the colors from other pages, Like: `Host-Dashboard`

**Comment by thevinitgupta** [comment]
Thanks @AliReza1083

**Comment by alisamadiii** [comment]
How is it going?

**Comment by thevinitgupta** [comment]
I have done progress. 
Currently working on responsiveness.
![image](https://user-images.githubusercontent.com/65801700/211308781-5bff5cd1-0b62-4554-8e6f-0dede1674707.png)

**Comment by alisamadiii** [comment]
It's looking nice,
Great job

**Comment by alisamadiii** [comment]
Can we know what is the name of the file that you are currently working on?

**Comment by thevinitgupta** [comment]
Yes, I named it as you specified : `space-light.js` in the pages folder
