### ISSUE TITLE
[Bug] Contributors

### ISSUE THREAD

**Issue by alisamadiii** [avie-dev/spaceslounge#53]
### Description

We need to add three other contributors on the page, and they're:
1. Jeson
2. Luiz
3. Zona

Note:- We have to check all the links for being sure whether they are correct or not.

### Additional information

You just need to work with contributors.json file which is located in `./src/content/contributors.json`.

**Comment by jaynarayan-vaishnav** [comment]
Will work on it thanks for assigning @AliReza1083

**Comment by alisamadiii** [comment]
Awesome, Good Luck
