### ISSUE TITLE
[FEATURE] Footer

### ISSUE THREAD

**Issue by alisamadiii** [avie-dev/spaceslounge#54]
### Description

Right now, There is a footer but we can develop it to look beautiful.

How to access the files that We need for this issue:

1. The **File** that We must work is located in `./src/components/Footer/Footer.js`
2. We can check the design [here](https://www.figma.com/file/YMoSJKWhHTakMAWpCozZ7D/Spaces-Lounge?node-id=0%3A1&t=mgnVpTuRa2LXvQ2c-1)
3. We can access the logo in `./public/Header img.png`

The links that We should add as `href`:
- Host - `/host`
- Speaker - `/speaker`
- Space Light - `/` (We'll tell you later)
- GitHub - `https://github.com/avie-dev/spaceslounge`
- discord - `https://discord.gg/4ccommunity`

### Screenshots

![image](https://user-images.githubusercontent.com/99729607/211312562-ac0fbc02-794d-4c65-ac01-6f967cd4c07f.png)
![image](https://user-images.githubusercontent.com/99729607/211312618-07a1bff0-c413-4f29-a6ea-91441f4d0bbd.png)

### Additional information

Feel free to take this issue and tell us a deadline.

**Comment by Succyvibe** [comment]
I want to work on the Footer section. 
Deadline: 11/01/2023

**Comment by alisamadiii** [comment]
Awesome Succyvibe,
This issue will be assigned to you.
Good Luck

**Comment by Succyvibe** [comment]
Thanks my pleasure

**Comment by alisamadiii** [comment]
How is it going?

**Comment by Succyvibe** [comment]
Just sent a PR

**Comment by alisamadiii** [comment]
I commented on your PR @Succyvibe

**Comment by alisamadiii** [comment]
Done by @Succyvibe
