### ISSUE TITLE
[FEATURE] One link in Navbar must be deleted

### ISSUE THREAD

**Issue by alisamadiii** [avie-dev/spaceslounge#57]
### Description

For this website, We don't need `sign up` button, because the user can only sign in with twitter auth.
That's why we need to remove one link.

Current Navbar:
![image](https://user-images.githubusercontent.com/99729607/211420067-3826450a-f8de-4bbd-a1e4-b96ee7d763b1.png)

How to access the files that We need for this issue:

- The File that We must work is located in `./src/components/Navbar/navbar.jsx`

### Screenshots

The new design that we want to have instead of the current one.

![image](https://user-images.githubusercontent.com/99729607/211420156-77418ca7-6815-448c-9852-644a906ba0f4.png)
![image](https://user-images.githubusercontent.com/99729607/211420275-acbcb474-5191-4ded-b93d-77f88bf4b4d0.png)

**Comment by AliReza1083** [comment]
Hi @thevinitgupta,
Are you willing to work on this as well?
It won't take your much time.

**Comment by Helper2005** [comment]
I'll work on this issue,
Please assign it to me

**Comment by alisamadiii** [comment]
Good Luck
