### ISSUE TITLE
[FEATURE] Sign in Page

### ISSUE THREAD

**Issue by alisamadiii** [avie-dev/spaceslounge#58]
### Description

Right now, There is a section for it but we can develop it to look beautiful.

Current Design:
![image](https://user-images.githubusercontent.com/99729607/211422639-c8647d08-a10b-4767-9d57-524ed20726de.png)

How to access the files that We need for this issue:

- The File that We must work is located in `./src/pages/sign-up.js`
- We can check the design [here](https://www.figma.com/file/YMoSJKWhHTakMAWpCozZ7D/Spaces-Lounge?node--id=0%3A1&t=mgnVpTuRa2LXvQ2c-1)

### Screenshots

The new design that we want to have instead of the current one.

![image](https://user-images.githubusercontent.com/99729607/211422672-2d8d4202-6978-4710-bfe1-05e818e441b3.png)
![image](https://user-images.githubusercontent.com/99729607/211422680-3d93b511-0d33-40a0-8834-ee462c78b970.png)

### Additional information

We'll talk about some details once this issue is assigned you.

**Comment by Mayank-KS** [comment]
I am assigning it to myself if that is ok with you @AliReza1083

**Comment by alisamadiii** [comment]
Ok, that's okay.
Good luck

**Comment by alisamadiii** [comment]
How is it going?

**Comment by alisamadiii** [comment]
How is it going, Mayank?

**Comment by Sayan-Maity** [comment]
Hey @AliReza1083 @Mayank-KS , is the above enhancement in the sign in page done, or else I am interested in contributing to the project

**Comment by Mayank-KS** [comment]
ok go for it 

> Hey @AliReza1083 @Mayank-KS , is the above enhancement in the sign in page done, or else I am interested in contributing to the project

Yeah go for it

**Comment by alisamadiii** [comment]
@Mayank-KS,
Can we close your PR or...?

**Comment by Mayank-KS** [comment]
yeah you can

**Comment by alisamadiii** [comment]
How is it going @Sayan-Maity ?

**Comment by Sayan-Maity** [comment]
Hey @AliReza1083 , I was waiting for the response, will complete it within couple of days

**Comment by alisamadiii** [comment]
Sorry @Sayan-Maity 
We didn't assign it to you, but you can start working on this issue.

**Comment by Sayan-Maity** [comment]
Okay cool,

**Comment by alisamadiii** [comment]
Any Updates?

**Comment by Sayan-Maity** [comment]
Hey @AliReza1083, I tried but the thing is the violet shadow am not able to apply, I can only apply two waves with one single color

**Comment by alisamadiii** [comment]
Hi @Sayan-Maity,
You can take a look at the design inside [here](https://www.figma.com/file/YMoSJKWhHTakMAWpCozZ7D/Spaces-Lounge?node-id=0%3A1&t=ibYEFomjEF2pHCyY-1).

The steps that you can solve the issue:

1. There are two SVGs, So combine them into a group.
2. Export them as SVG
3. Now, you can use them into the page.

Hope that makes sense.

Feel free to ask anytime when you get stuck :)

**Comment by Sayan-Maity** [comment]
Oh I was trying to make the waves using clip path css, okay will have a look there !!

**Comment by alisamadiii** [comment]
> Oh I was trying to make the waves using clip path css, okay will have a look there !!

You will make your work hard with clip path :)

**Comment by Sayan-Maity** [comment]
Yeah right, okay I will look upon the svg's

**Comment by gambhirsharma** [comment]
@Sayan-Maity are you working on this project? If not @AliReza1083 you can assign these tasks to me.

**Comment by Sayan-Maity** [comment]
> @Sayan-Maity are you working on this project? If not @AliReza1083 you can assign these tasks to me.

no am not working on it @gambhirsharma

**Comment by alisamadiii** [comment]
> @Sayan-Maity are you working on this project? If not @AliReza1083 you can assign these tasks to me.

Yeah, You can take it.

**Comment by alisamadiii** [comment]
Yeah, It is looking great, @gambhirsharma!
Well done

**Comment by gambhirsharma** [comment]
Sorry, @AliReza1083 there was some issue with the SVG. The black stroke was appearing in the wave let me make the required change and open a PR.

<img width="1440" alt="Screenshot 2023-05-17 at 2 05 34 PM" src="https://github.com/avie-dev/spaceslounge/assets/69895353/6815d8ad-cb0d-490d-97b1-f9c98bf9b431">
