### ISSUE TITLE
Increase the line height of the text on the landing page

### ISSUE THREAD

**Issue by mohammadshaad** [avie-dev/spaceslounge#66]
### Description

I want to increase the line height of the para after the SpaceLounge heading text on the landing page. 

### Screenshots

![image](https://user-images.githubusercontent.com/89409389/212524619-7148ac64-d3e6-46f1-b556-225673ab3a34.png)

**Comment by mohammadshaad** [comment]
@AliReza1083 kindly assign me this issue

**Comment by alisamadiii** [comment]
That's great.
This issue will be assigned to you.
Good luck
