### ISSUE TITLE
The Page text doesn't have any use in footer

### ISSUE THREAD

**Issue by rohinish404** [avie-dev/spaceslounge#76]
### Description

The Page text doesn't have any use in footer. Maybe we can make it a link to the top or home page.
<img width="1435" alt="Screenshot 2023-01-25 at 9 51 22 PM" src="https://user-images.githubusercontent.com/92542124/214619085-88eeb5c2-0bc8-49a9-b4e4-c92af3e598a1.png">

**Comment by alisamadiii** [comment]
Yeah, That is a good idea.
Are you willing to make it?

**Comment by rohinish404** [comment]
Yeah.. i'll add so that it links to the home page.

**Comment by alisamadiii** [comment]
That is great.
This issue will be assigned to you.
Good luck.

**Comment by rohinish404** [comment]
I've made a pr regarding this. You can check that:)

**Comment by alisamadiii** [comment]
Done ✅🎉
