### ISSUE TITLE
[DOCS] <Spaces lounge Documentation update>

### ISSUE THREAD

**Issue by Kirtikagoyal** [avie-dev/spaceslounge#78]
### Description

we should create a new and clean documentation for our website.

**Comment by alisamadiii** [comment]
That is a good idea.
This issue will be assigned to you.
If you want any help, You could talk with Eno, he has the responsibility to make wireframes or documents for the website.
Good Luck

**Comment by vikaskumar2703** [comment]
Hi @Kirtikagoyal . I am looking for some repos to contribute to as beginner . Can i in anyway help you in writing the documentation for the website.

**Comment by Kirtikagoyal** [comment]
sure @vikaskumar2703, appreciate your help.
ping me on discord spaces lounge channel, we can discuss there about completing the documentation.

**Comment by Mayank-KS** [comment]
How is the issue progressing??

**Comment by Kirtikagoyal** [comment]
The readme is ready. i'll close the issue today.

**Comment by alisamadiii** [comment]
Done ✅
